version: 2

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:228.0.0
    steps:
      - checkout
      - run: sudo apt-get install build-essential
      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
      - run: echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
      - run: echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run: nvm install 9.11.1
      - run: nvm use 9.11.1
      - run: npm install
      - run: echo $GCLOUD_SERVICE_KEY
      - run: echo $GOOGLE_PROJECT_ID
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: node index.js
      - run: gsutil cp -Z build/js/data.js gs://public-tree-map/js/
      - run: gsutil setmeta -h "Cache-Control:public, max-age=43200" gs://public-tree-map/js/data.js
      - run: gsutil -m cp -r build/img gs://public-tree-map/

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          # Midnight PST is 8am UTC
          cron: "0 8 * * *"
          filters:
            branches:
              only: master
    jobs:
      - deploy
